import { Prisma } from '.prisma/client';
export {
  FamilyObject,
  FamilyIdFieldObject,
  FamilyOwnerIdFieldObject,
  FamilyNameFieldObject,
  FamilyOwnerFieldObject,
  FamilyMembersFieldObject,
  FamilyCreatedAtFieldObject,
  FamilyUpdatedAtFieldObject,
  createManyFamilyMutation,
  createOneFamilyMutation,
  deleteManyFamilyMutation,
  deleteOneFamilyMutation,
  updateManyFamilyMutation,
  updateOneFamilyMutation,
  upsertOneFamilyMutation,
  createManyFamilyMutationObject,
  createOneFamilyMutationObject,
  deleteManyFamilyMutationObject,
  deleteOneFamilyMutationObject,
  updateManyFamilyMutationObject,
  updateOneFamilyMutationObject,
  upsertOneFamilyMutationObject,
  findFirstFamilyQuery,
  findManyFamilyQuery,
  countFamilyQuery,
  findUniqueFamilyQuery,
  findFirstFamilyQueryObject,
  findManyFamilyQueryObject,
  countFamilyQueryObject,
  findUniqueFamilyQueryObject
} from './Family';
export {
  GuestObject,
  GuestIdFieldObject,
  GuestFamilyIdFieldObject,
  GuestStatusFieldObject,
  GuestPasswordFieldObject,
  GuestEmailFieldObject,
  GuestFirst_nameFieldObject,
  GuestLast_nameFieldObject,
  GuestSideFieldObject,
  GuestTypeFieldObject,
  GuestAgeFieldObject,
  GuestSexFieldObject,
  GuestTableFieldObject,
  GuestTransferFieldObject,
  GuestAccommodationFieldObject,
  GuestFamilyFieldObject,
  GuestOwnedFamilyFieldObject,
  GuestEventsFieldObject,
  GuestCreatedAtFieldObject,
  GuestUpdatedAtFieldObject,
  createManyGuestMutation,
  createOneGuestMutation,
  deleteManyGuestMutation,
  deleteOneGuestMutation,
  updateManyGuestMutation,
  updateOneGuestMutation,
  upsertOneGuestMutation,
  createManyGuestMutationObject,
  createOneGuestMutationObject,
  deleteManyGuestMutationObject,
  deleteOneGuestMutationObject,
  updateManyGuestMutationObject,
  updateOneGuestMutationObject,
  upsertOneGuestMutationObject,
  findFirstGuestQuery,
  findManyGuestQuery,
  countGuestQuery,
  findUniqueGuestQuery,
  findFirstGuestQueryObject,
  findManyGuestQueryObject,
  countGuestQueryObject,
  findUniqueGuestQueryObject
} from './Guest';
export {
  EventObject,
  EventIdFieldObject,
  EventIndexFieldObject,
  EventAliasFieldObject,
  EventNameFieldObject,
  EventDateFieldObject,
  EventStartFieldObject,
  EventEndFieldObject,
  EventDescriptionFieldObject,
  EventAddressFieldObject,
  EventUrlFieldObject,
  EventGuestsFieldObject,
  EventCreatedAtFieldObject,
  EventUpdatedAtFieldObject,
  createManyEventMutation,
  createOneEventMutation,
  deleteManyEventMutation,
  deleteOneEventMutation,
  updateManyEventMutation,
  updateOneEventMutation,
  upsertOneEventMutation,
  createManyEventMutationObject,
  createOneEventMutationObject,
  deleteManyEventMutationObject,
  deleteOneEventMutationObject,
  updateManyEventMutationObject,
  updateOneEventMutationObject,
  upsertOneEventMutationObject,
  findFirstEventQuery,
  findManyEventQuery,
  countEventQuery,
  findUniqueEventQuery,
  findFirstEventQueryObject,
  findManyEventQueryObject,
  countEventQueryObject,
  findUniqueEventQueryObject
} from './Event';
import { builder } from '../builder';

export const BatchPayload = builder.objectType(builder.objectRef<Prisma.BatchPayload>('BatchPayload'), {
  description: 'Batch payloads from prisma.',
  fields: (t) => ({
    count: t.exposeInt('count', { description: 'Prisma Batch Payload', nullable: false }),
  }),
});

export const modelNames = [
  'Family',
  'Guest',
  'Event',
] as const;

export type Model = typeof modelNames[number];
