export const DRESSCODE_COLOR_ERRORS = {
  DRESSCODE_COLOR_ALREADY_EXISTS: 'DRESSCODE_COLOR_ALREADY_EXISTS',
  DRESSCODE_COLOR_NOT_FOUND: 'DRESSCODE_COLOR_NOT_FOUND',
  DRESSCODE_COLOR_BAD_OWNER: 'DRESSCODE_COLOR_BAD_OWNER',
  DRESSCODE_COLOR_UNKNOWN_ERROR: 'DRESSCODE_COLOR_UNKNOWN_ERROR',
} as const

export type DRESSCODE_COLOR_ERRORS =
  (typeof DRESSCODE_COLOR_ERRORS)[keyof typeof DRESSCODE_COLOR_ERRORS]

export class DresscodeColorError extends Error {
  constructor(key: DRESSCODE_COLOR_ERRORS) {
    super(key)
    this.name = 'DresscodeColorException'
  }
}
