name: CI (develop)
on:
  push:
    branches:
      - "develop"
  workflow_dispatch:

env:
  NODE_VERSION: 20

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Настройка Node
        uses: actions/setup-node@v4
        with:
          node-version: "${{ env.NODE_VERSION }}"
          cache: "yarn"

      - name: Получение пути к кэшу
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Установка зависимостей
        run: yarn --prefer-offline

  build-local:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Чтение репозитория
        uses: actions/checkout@v2

      - name: Установка ноды
        uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE_VERSION }}"

      - name: Извлечение node_modules
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Сборка сервисов
        run: yarn turbo build --filter=api --filter=bot --filter=web

      - name: Загрузка артефактов
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            apps/*/dist
            packages/*/dist

  test-unit:
    runs-on: ubuntu-latest
    needs: build-local
    steps:
      - name: Чтение репозитория
        uses: actions/checkout@v2

      - name: Установка ноды
        uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE_VERSION }}"

      - name: Загрузка артефактов
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Запуск юнит-тестов
        run: yarn turbo test:ci

  test-server:
    runs-on: ubuntu-latest
    needs: build-local
    steps:
      - name: Чтение репозитория
        uses: actions/checkout@v2

      - name: Установка ноды
        uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE_VERSION }}"

      - name: Загрузка артефактов
        uses: actions/download-artifact@v4
        with:
          name: dist

      - run: echo "${{ secrets.TEST_SERVER_ENV }}" >> ./apps/api/.env && echo 'VERSION=$GITHUB_SHA' >> ./apps/api/.env
      - run: CI=true yarn turbo test:server
