name: CI (main)
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Релиз
    runs-on: ubuntu-latest
    steps:
      - name: Чтение репозитоиря
        uses: actions/checkout@v2
      - name: Создание релиза
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: "./CHANGELOG.md"
          draft: false
          prerelease: false
